package httpapi

const (
	problemContentType                   = "application/problem+json"
	problemTitleUnauthorized             = "Unauthorized"
	problemTitleInternalServer           = "Internal Server Error"
	problemTitleBadRequest               = "Bad Request"
	problemTitleNotFound                 = "Not Found"
	problemDetailInvalidJSON             = "dữ liệu gửi lên không hợp lệ"
	problemCodeAuthRequired              = "AUTH_REQUIRED"
	problemCodeCategoryLoadFailed        = "CATEGORY_LOAD_FAILED"
	problemCodeCategorySaveFailed        = "CATEGORY_SAVE_FAILED"
	problemCodeCategoryNotFound          = "CATEGORY_NOT_FOUND"
	problemCodeWalletLoadFailed          = "WALLET_LOAD_FAILED"
	problemCodeWalletSaveFailed          = "WALLET_SAVE_FAILED"
	problemCodeWalletNotFound            = "WALLET_NOT_FOUND"
	problemCodeTransactionLoadFailed     = "TRANSACTION_LOAD_FAILED"
	problemCodeTransactionSaveFailed     = "TRANSACTION_SAVE_FAILED"
	problemCodeTransactionNotFound       = "TRANSACTION_NOT_FOUND"
	problemCodeTransactionWalletNotFound = "TRANSACTION_WALLET_NOT_FOUND"
	problemCodeAuthInvalidFormat         = "AUTH_INVALID_FORMAT"
	problemCodeTokenInvalid              = "TOKEN_INVALID"
	problemCodeSessionExpired            = "SESSION_EXPIRED"
	problemCodeSessionVerifyFailed       = "SESSION_VERIFY_FAILED"
	problemCodeUserNotFound              = "USER_NOT_FOUND"
	problemCodeProfileLoadFailed         = "PROFILE_LOAD_FAILED"
	problemCodeHomeLoadFailed            = "HOME_LOAD_FAILED"
	problemCodeBadRequest                = "BAD_REQUEST"
	problemCodeLoginFailed               = "LOGIN_FAILED"
	problemCodeGoogleUnavailable         = "GOOGLE_LOGIN_UNAVAILABLE"
	problemCodeGoogleStateInvalid        = "GOOGLE_STATE_INVALID"
	problemCodeGoogleProfileInvalid      = "GOOGLE_PROFILE_INVALID"
	problemCodeEmailNotAllowed           = "EMAIL_NOT_ALLOWED"
)
