import { Banknote, BriefcaseBusiness, Car, ChartNoAxesCombined, Coffee, Gamepad2, Gift, GraduationCap, HandCoins, HeartPulse, House, Landmark, PiggyBank, Plane, Receipt, ReceiptText, Salad, ShieldCheck, ShoppingBag, Soup, Tags, Utensils, type LucideIcon } from "lucide-react";
import type { ICON_BADGE_TONES } from "./tokens";

type CategoryPresentation = { icon: LucideIcon; tone: keyof typeof ICON_BADGE_TONES };

const CATEGORY_PRESENTATIONS: Record<string, CategoryPresentation> = {
  expense_food: { icon: Utensils, tone: "categoryOrange" },
  expense_bills: { icon: ReceiptText, tone: "categoryBlue" },
  expense_shopping: { icon: ShoppingBag, tone: "categoryViolet" },
  expense_family: { icon: House, tone: "categoryRose" },
  expense_transport: { icon: Car, tone: "categorySky" },
  expense_health: { icon: HeartPulse, tone: "categoryRed" },
  expense_education: { icon: GraduationCap, tone: "categoryIndigo" },
  expense_entertainment: { icon: Gamepad2, tone: "categoryFuchsia" },
  expense_gifts: { icon: Gift, tone: "categoryPink" },
  expense_insurance: { icon: ShieldCheck, tone: "categoryTeal" },
  expense_investment: { icon: ChartNoAxesCombined, tone: "categoryEmerald" },
  expense_travel: { icon: Plane, tone: "categoryCyan" },
  expense_savings: { icon: PiggyBank, tone: "categoryLime" },
  expense_business: { icon: BriefcaseBusiness, tone: "categoryAmber" },
  expense_general: { icon: Receipt, tone: "categorySlate" },
  income_root: { icon: Banknote, tone: "categoryIncome" },
  debt_root: { icon: HandCoins, tone: "categoryDebt" },
  expense_food_snacks: { icon: Salad, tone: "categoryOrange" },
  expense_food_coffee: { icon: Coffee, tone: "categoryAmber" },
  expense_food_meals: { icon: Soup, tone: "categoryOrange" },
  expense_bills_phone: { icon: Landmark, tone: "categoryBlue" },
  expense_bills_water: { icon: Landmark, tone: "categoryBlue" },
  expense_bills_electricity: { icon: Landmark, tone: "categoryAmber" },
  expense_bills_gas: { icon: Landmark, tone: "categoryAmber" },
  expense_bills_tv: { icon: Landmark, tone: "categoryBlue" },
  expense_bills_internet: { icon: Landmark, tone: "categoryBlue" },
  expense_bills_rent: { icon: House, tone: "categoryRose" },
  expense_bills_other: { icon: ReceiptText, tone: "categoryBlue" },
  expense_shopping_personal: { icon: ShoppingBag, tone: "categoryViolet" },
  expense_shopping_household: { icon: House, tone: "categoryViolet" },
  expense_shopping_beauty: { icon: Gift, tone: "categoryPink" },
  expense_family_home_decor: { icon: House, tone: "categoryRose" },
  expense_family_services: { icon: House, tone: "categoryRose" },
  expense_family_pets: { icon: HeartPulse, tone: "categoryRose" },
  expense_transport_maintenance: { icon: Car, tone: "categorySky" },
  expense_health_checkup: { icon: HeartPulse, tone: "categoryRed" },
  expense_health_fitness: { icon: HeartPulse, tone: "categoryRed" },
  expense_entertainment_online: { icon: Gamepad2, tone: "categoryFuchsia" },
  expense_entertainment_fun: { icon: Gamepad2, tone: "categoryFuchsia" },
  expense_transfer_out: { icon: Landmark, tone: "categorySlate" },
  expense_interest_paid: { icon: Banknote, tone: "categorySlate" },
  expense_uncategorized: { icon: Tags, tone: "categorySlate" },
  expense_withdrawal: { icon: Banknote, tone: "categorySlate" },
  expense_accessories: { icon: ShoppingBag, tone: "categoryViolet" },
  expense_books: { icon: GraduationCap, tone: "categoryIndigo" },
  expense_charity: { icon: HeartPulse, tone: "categoryPink" },
  expense_funeral: { icon: Gift, tone: "categorySlate" },
  expense_games: { icon: Gamepad2, tone: "categoryFuchsia" },
  expense_home_repair: { icon: House, tone: "categoryRose" },
  expense_wedding: { icon: Gift, tone: "categoryPink" },
  expense_movies: { icon: Gamepad2, tone: "categoryFuchsia" },
  expense_parking: { icon: Car, tone: "categorySky" },
  expense_personal_care: { icon: HeartPulse, tone: "categoryPink" },
  expense_fuel: { icon: Car, tone: "categorySky" },
  expense_medicine: { icon: HeartPulse, tone: "categoryRed" },
  expense_restaurant: { icon: Utensils, tone: "categoryOrange" },
  expense_sports: { icon: HeartPulse, tone: "categoryRed" },
  expense_taxi: { icon: Car, tone: "categorySky" },
  expense_children: { icon: HeartPulse, tone: "categoryRose" },
  expense_clothes: { icon: ShoppingBag, tone: "categoryViolet" },
  expense_medical_treatment: { icon: HeartPulse, tone: "categoryRed" },
  expense_electronics: { icon: Landmark, tone: "categoryIndigo" },
  expense_cost: { icon: Receipt, tone: "categorySlate" },
  expense_shoes: { icon: ShoppingBag, tone: "categoryViolet" },
  expense_friends: { icon: HeartPulse, tone: "categoryPink" },
  income_salary: { icon: Banknote, tone: "categoryIncome" },
  income_other: { icon: Landmark, tone: "categoryIncome" },
  income_transfer_in: { icon: Landmark, tone: "categoryIncome" },
  income_interest: { icon: Banknote, tone: "categoryIncome" },
  income_uncategorized: { icon: Tags, tone: "categoryIncome" },
  income_gift: { icon: Gift, tone: "categoryIncome" },
  income_bonus: { icon: Gift, tone: "categoryIncome" },
  income_sell_items: { icon: ShoppingBag, tone: "categoryIncome" },
  debt_lend: { icon: HandCoins, tone: "categoryDebt" },
  debt_repay: { icon: Receipt, tone: "categoryDebt" },
  debt_loan: { icon: Landmark, tone: "categoryDebt" },
  debt_collect: { icon: Banknote, tone: "categoryDebt" },
};

const DEFAULT_CATEGORY_PRESENTATION: CategoryPresentation = { icon: Tags, tone: "categorySlate" };

export function categoryPresentationFor(systemKey?: string | null): CategoryPresentation {
  return systemKey ? CATEGORY_PRESENTATIONS[systemKey] ?? DEFAULT_CATEGORY_PRESENTATION : DEFAULT_CATEGORY_PRESENTATION;
}
