import { createServer } from 'vite';
import { strict as assert } from 'node:assert';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

const server = await createServer({ server: { middlewareMode: true }, appType: 'custom' });
try {
  const { BaseButton } = await server.ssrLoadModule('/src/atomic/atoms/BaseButton.tsx');
  const { SurfaceCard } = await server.ssrLoadModule('/src/atomic/atoms/SurfaceCard.tsx');
  const { StatusMessage } = await server.ssrLoadModule('/src/atomic/atoms/StatusMessage.tsx');
  const { Progress, BudgetGauge } = await server.ssrLoadModule('/src/atomic/atoms/Progress.tsx');
  const { BaseTextInput } = await server.ssrLoadModule('/src/atomic/atoms/FormField.tsx');
  const { BaseCategoryTree } = await server.ssrLoadModule('/src/atomic/molecules/BaseCategoryTree.tsx');
  const { CategoryTreeSelector } = await server.ssrLoadModule('/src/atomic/molecules/CategoryTreeSelector.tsx');
  const { WalletEditorForm, EMPTY_WALLET_FORM } = await server.ssrLoadModule('/src/atomic/molecules/WalletEditorForm.tsx');
  const { BaseDonutChart } = await server.ssrLoadModule('/src/atomic/molecules/BaseCharts.tsx');
  const { WalletCreateForm, WalletTypePicker, canCreateWallet } = await server.ssrLoadModule('/src/atomic/molecules/WalletCreateForm.tsx');
  const { savingsProgress, SavingsSummary } = await server.ssrLoadModule('/src/atomic/molecules/SavingsSummary.tsx');
  const { WalletSelectionList } = await server.ssrLoadModule('/src/atomic/molecules/WalletSelectionList.tsx');
  const { FeedbackFloatingBubble } = await server.ssrLoadModule('/src/atomic/organisms/FeedbackFloatingBubble.tsx');
  const html = (component, props) => renderToStaticMarkup(React.createElement(component, props));
  const { BudgetProgressItem } = await server.ssrLoadModule('/src/atomic/molecules/BudgetProgressItem.tsx');
  const { Wallet } = await server.ssrLoadModule('lucide-react');
  const maskedBudget=html(BudgetProgressItem,{budget:{name:'Private',spent:123456,limit:200000,icon:Wallet},masked:true});
  assert.doesNotMatch(maskedBudget,/123[.,]456|200[.,]000/);
  const { apiRequest } = await server.ssrLoadModule('/src/services/api.ts');
  const { budgetDateInput } = await server.ssrLoadModule('/src/services/budgetDates.ts');
  const priorTZ=process.env.TZ;
  try {
    process.env.TZ='UTC';
    const utcLabels=budgetDateInput('2026-08-31','2026-09-30');
    process.env.TZ='America/Los_Angeles';
    assert.deepEqual(budgetDateInput('2026-08-31','2026-09-30'),utcLabels);
    assert.deepEqual(utcLabels,{start_date:'2026-08-31',end_date:'2026-09-30'});
  } finally {if(priorTZ===undefined)delete process.env.TZ;else process.env.TZ=priorTZ;}
  const originalFetch=globalThis.fetch;
  try {
    globalThis.fetch=async()=>new Response(JSON.stringify({detail:'Overlapping interval'}),{status:409,headers:{'content-type':'application/problem+json'}});
    await assert.rejects(()=>apiRequest('/api/v1/budgets'),error=>error.message==='Overlapping interval');
  } finally {globalThis.fetch=originalFetch;}
  const loading = html(BaseButton, { loading:true, children:'Save' });
  const empty = html(StatusMessage, { variant:'plain', children:'Chưa có giao dịch.' });
  assert.match(empty, /role="status"/);
  assert.match(empty, /Chưa có giao dịch\./);
  assert.doesNotMatch(empty, /\b(?:border|shadow|bg)-|<section/);
  const error = html(StatusMessage, { tone:'danger', children:'Error' });
  assert.match(error, /role="alert"/);
  assert.match(error, /border-danger-line/);
  assert.match(loading, /disabled=""/); assert.match(loading, /aria-busy="true"/); assert.match(loading, /bg-brand/);
  const flat = html(SurfaceCard, {elevation:'flat',children:'x'}); assert.match(flat,/shadow-none/); assert.doesNotMatch(flat,/shadow-card/);
  assert.match(html(Progress,{value:115,label:'Food'}),/aria-valuenow="100"/);
  assert.match(html(Progress,{value:-10,label:'Food'}),/aria-valuenow="0"/);
  assert.match(html(BudgetGauge,{value:115,label:'Food'}),/stroke-danger/);
  const inline = html(BaseTextInput,{variant:'inline','aria-label':'Name'}); assert.doesNotMatch(inline,/border-line/); assert.match(inline,/focus-visible:outline-action/);
  const selectingTree = html(BaseCategoryTree,{mode:'selection',selectedID:'child',root:{id:'root',name:'Food',subtitle:'Default group',isSystem:true,isEditable:true},children:[{id:'child',name:'Coffee',subtitle:'Personal group',isSystem:false,isEditable:true}],onSelect(){}});
  assert.equal((selectingTree.match(/aria-pressed="true"/g)??[]).length,1,'category tree selection mode marks the chosen row');
  assert.equal((selectingTree.match(/aria-pressed="false"/g)??[]).length,1,'category tree selection mode exposes sibling rows as selectable controls');
  const categories=[{id:'root',parent_id:null,kind:'expense',name:'Food',system_key:'expense_food',icon_key:'expense_food',is_system:true,wallet_ids:[]},{id:'child',parent_id:'root',kind:'expense',name:'Coffee',system_key:null,icon_key:'expense_coffee',is_system:false,wallet_ids:[]}];
  const treePicker=html(CategoryTreeSelector,{categories,selectableIDs:['child'],selectedID:'child',onSelect(){}});
  assert.match(treePicker,/aria-pressed="true"/,'category picker preserves selected child group');
  assert.match(treePicker,/Không áp dụng cho lựa chọn này/,'non-selectable parent remains visible as tree context');
  assert.match(treePicker,/Không chọn nhóm/,'category picker provides its clear-selection action');
  const wallet = html(WalletEditorForm,{state:EMPTY_WALLET_FORM,saving:true,onChange(){},onSubmit(){},onCancel(){}});
  assert.equal((wallet.match(/disabled=""/g) ?? []).length,6); // name, balance, checkbox, select, save and cancel
  assert.doesNotMatch(wallet, /Ghi chú/);
  assert.match(html(WalletEditorForm,{state:EMPTY_WALLET_FORM,saving:false,editing:true,onChange(){},onSubmit(){},onCancel(){}}), /Ghi chú/);
  assert.match(html(BaseDonutChart,{shares:[],center:'No data'}),/var\(--color-line\)/);
  assert.equal(canCreateWallet(EMPTY_WALLET_FORM),false);
  const valid={...EMPTY_WALLET_FORM,name:'Tiền mặt'};
  assert.equal(canCreateWallet(valid),true);
  assert.equal(canCreateWallet({...valid,openingBalance:'1abc'}),false);
  assert.equal(canCreateWallet({...valid,type:'goal',targetAmount:'0'}),false);
  assert.equal(canCreateWallet({...valid,type:'credit',creditLimit:'1000000'}),true);
  const create=html(WalletCreateForm,{state:valid,saving:false,onChange(){},onSubmit(){},onSelectType(){}});
  assert.doesNotMatch(create,/Ghi chú/);
  assert.match(create,/<select/);
  assert.match(create,/role="switch"/);
  assert.match(create,/VND — Đồng Việt Nam/);
  const excluded=html(WalletCreateForm,{state:{...valid,isInTotal:false},saving:false,onChange(){},onSubmit(){},onSelectType(){}});
  assert.match(excluded,/checked=""/);
  const picker=html(WalletTypePicker,{value:'goal',onSelect(){}});
  assert.equal((picker.match(/aria-pressed="true"/g)??[]).length,1);
  for(const label of ['Ví thường','Ví tiết kiệm','Ví tín dụng']) assert.ok(picker.includes(label));
  assert.deepEqual(savingsProgress(120,100),{remaining:0,percentage:100,reached:true});
  assert.deepEqual(savingsProgress(20,100),{remaining:80,percentage:20,reached:false});
  assert.deepEqual(savingsProgress(-10,100),{remaining:110,percentage:0,reached:false});
  const goalForm=html(WalletCreateForm,{state:{...valid,type:'goal',targetAmount:'1000',targetDate:'2026-12-31'},saving:false,onChange(){},onSubmit(){},onSelectType(){}});
  assert.match(goalForm,/type="date"/); assert.match(goalForm,/2026-12-31/);
  const goalWallet={id:'g',name:'Goal',type:'goal',currency:'VND',opening_balance:0,current_balance:20,target_amount:100,is_in_total:true};
  const { WalletDetailPanel } = await server.ssrLoadModule('/src/atomic/organisms/SavingsWalletPanel.tsx');
  const history=html(WalletDetailPanel,{wallet:goalWallet,categories:[{id:'interest',name:'Thu lãi',kind:'income',system_key:'income_interest',wallet_ids:[]}],transactions:[{id:'t',wallet_id:'g',category_id:'interest',type:'income',amount:20,occurred_at:'2026-09-20T00:00:00Z'}],onBack(){},onChanged(){}});
  assert.match(history,/Thu lãi/);
  assert.match(html(SavingsSummary,{wallet:goalWallet}),/aria-valuenow="20"/);
  const walletList=html(WalletSelectionList,{wallets:[goalWallet,{...goalWallet,id:'excluded',name:'Excluded',is_in_total:false}],selectedID:null,editing:false,onSelect(){},onAdd(){}});
  assert.match(walletList,/TÍNH VÀO TỔNG/); assert.match(walletList,/KHÔNG TÍNH VÀO TỔNG/);
  assert.equal((walletList.match(/aria-pressed="true"/g)??[]).length,1);
  const feedbackBubble=html(FeedbackFloatingBubble,{captureRoot:{current:null}});
  assert.match(feedbackBubble,/fixed bottom-24 right-4 z-40/);
  assert.match(feedbackBubble,/border-line bg-card shadow-sm/,'feedback bubble should use the shared surface icon treatment');
  assert.doesNotMatch(feedbackBubble,/border-action bg-brand/,'feedback bubble should not use a one-off brand treatment');
  console.log('Base contracts passed: loading, single elevation, clamped progress, danger gauge, inline input focus.');
} finally { await server.close(); }
